// city name
export const cities = [
   'Boston',
   'Las Vegas', 
   'San Jose',
];


// flight from Boston to Las Vegas (6 hrs)
// flight from Boston to San Jose (8 hrs)
// flight from Las Vegas to San Jose (2 hrs)
export const flightData = [
   {
      id: 1,
      fromCity: "Boston",
      toCity: "Las Vegas",
      flightNumber: 'BL01',
      departureTime: '1 AM',
      arrivalTime: '7 AM',
      seatAvailability: 2,
      price: 600,
   },
   {
      id: 2,
      fromCity: "Boston",
      toCity: "Las Vegas",
      flightNumber: 'BL02',
      departureTime: '2 AM',
      arrivalTime: '8 AM',
      seatAvailability: 4,
      price: 600,
   },
   {
      id: 4,
      fromCity: "Las Vegas",
      toCity: "Boston",
      flightNumber: 'LB04',
      departureTime: '4 AM',
      arrivalTime: '10 AM',
      seatAvailability: 8,
      price: 600,
   },
   {
      id: 5,
      fromCity: "Las Vegas",
      toCity: "Boston",
      flightNumber: 'LB05',
      departureTime: '5 AM',
      arrivalTime: '11 AM',
      seatAvailability: 10,
      price: 600,
   },
   {
      id: 6,
      fromCity: "Las Vegas",
      toCity: "San Jose",
      flightNumber: 'LS06',
      departureTime: '6 AM',
      arrivalTime: '8 AM',
      seatAvailability: 12,
      price: 200,
   },
   {
      id: 7,
      fromCity: "Las Vegas",
      toCity: "San Jose",
      flightNumber: 'LS07',
      departureTime: '7 AM',
      arrivalTime: '9 AM',
      seatAvailability: 14,
      price: 200,
   },
   {
      id: 8,
      fromCity: "San Jose",
      toCity: "Las Vegas",
      flightNumber: 'LS08',
      departureTime: '8 AM',
      arrivalTime: '10 AM',
      seatAvailability: 16,
      price: 200,
   },
   {
      id: 9,
      fromCity: "San Jose",
      toCity: "Las Vegas",
      flightNumber: 'LS09',
      departureTime: '9 AM',
      arrivalTime: '11 AM',
      seatAvailability: 18,
      price: 200,
   },
   {
      id: 10,
      fromCity: "Boston",
      toCity: "San Jose",
      flightNumber: 'BS10',
      departureTime: '10 AM',
      arrivalTime: '6 PM',
      seatAvailability: 20,
      price: 800,
   },
   {
      id: 11,
      fromCity: "Boston",
      toCity: "San Jose",
      flightNumber: 'BS11',
      departureTime: '11 AM',
      arrivalTime: '7 PM',
      seatAvailability: 22,
      price: 800,
   },
   {
      id: 12,
      fromCity: "San Jose",
      toCity: "Boston",
      flightNumber: 'SB12',
      departureTime: '12 PM',
      arrivalTime: '8 PM',
      seatAvailability: 24,
      price: 800,
   },
   {
      id: 13,
      fromCity: "San Jose",
      toCity: "Boston",
      flightNumber: 'SB13',
      departureTime: '1 PM',
      arrivalTime: '9 PM',
      seatAvailability: 26,
      price: 800,
   },
]
